/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retailers/item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Buscar un producto en uno o más retailers */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        query: string;
                        /** @default 15 */
                        limit?: number;
                        retailers?: ("carrefour" | "dia" | "jumbo" | "vea")[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            query: string;
                            limit: number;
                            retailers: ("carrefour" | "dia" | "jumbo" | "vea")[];
                            results: {
                                /** @enum {string} */
                                retailer: "carrefour" | "dia" | "jumbo" | "vea";
                                products: components["schemas"]["Product"][];
                                error?: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retailers/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Comparar una lista de compras en uno o más retailers */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        items: string[];
                        /** @default 15 */
                        limit?: number;
                        retailers?: ("carrefour" | "dia" | "jumbo" | "vea")[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: string[];
                            limit: number;
                            retailers: ("carrefour" | "dia" | "jumbo" | "vea")[];
                            best: null | {
                                /** @enum {string} */
                                retailer: "carrefour" | "dia" | "jumbo" | "vea";
                                total: number;
                                missingCount: number;
                                missingItems: string[];
                            };
                            ranking: {
                                /** @enum {string} */
                                retailer: "carrefour" | "dia" | "jumbo" | "vea";
                                total: number;
                                missingCount: number;
                                missingItems: string[];
                            }[];
                            detail: {
                                query: string;
                                results: {
                                    /** @enum {string} */
                                    retailer: "carrefour" | "dia" | "jumbo" | "vea";
                                    products: components["schemas"]["Product"][];
                                    error?: string;
                                }[];
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Product: {
            id?: string;
            name?: string;
            price?: number;
            listPrice?: number;
            link?: string;
            image?: string;
            retailer?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
